# BBM409 Assignment_0
Group Member: Oğuzhan Taşçı

Group Member: İbrahim Enes Genişyürek

In [1]:
# import necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
# Read dataset from PC
df = pd.read_csv("star_classification.csv")

In [3]:
df

obj_ID       alpha      delta         u         g         r  \
0      1.237661e+18  135.689107  32.494632  23.87882  22.27530  20.39501   
1      1.237665e+18  144.826101  31.274185  24.77759  22.83188  22.58444   
2      1.237661e+18  142.188790  35.582444  25.26307  22.66389  20.60976   
3      1.237663e+18  338.741038  -0.402828  22.13682  23.77656  21.61162   
4      1.237680e+18  345.282593  21.183866  19.43718  17.58028  16.49747   
...             ...         ...        ...       ...       ...       ...   
99995  1.237679e+18   39.620709  -2.594074  22.16759  22.97586  21.90404   
99996  1.237679e+18   29.493819  19.798874  22.69118  22.38628  20.45003   
99997  1.237668e+18  224.587407  15.700707  21.16916  19.26997  18.20428   
99998  1.237661e+18  212.268621  46.660365  25.35039  21.63757  19.91386   
99999  1.237661e+18  196.896053  49.464643  22.62171  21.79745  20.60115   

              i         z  run_ID  rerun_ID  cam_col  field_ID   spec_obj_ID  \
0      19.16573  18.79371    3606       301        2        79  6.543777e+18   
1      21.16812  21.61427    4518       301        5       119  1.176014e+19   
2      19.34857  18.94827    3606       301        2       120  5.152200e+18   
3      20.50454  19.25010    4192       301        3       214  1.030107e+19   
4      15.97711  15.54461    8102       301        3       137  6.891865e+18   
...         ...       ...     ...       ...      ...       ...           ...   
99995  21.30548  20.73569    7778       301        2       581  1.055431e+19   
99996  19.75759  19.41526    7917       301        1       289  8.586351e+18   
99997  17.69034  17.35221    5314       301        4       308  3.112008e+18   
99998  19.07254  18.62482    3650       301        4       131  7.601080e+18   
99999  20.00959  19.28075    3650       301        4        60  8.343152e+18   

        class  redshift  plate    MJD  fiber_ID  
0      GALAXY  0.634794   5812  56354       171  
1      GALAXY  0.779136  10445  58158       427  
2      GALAXY  0.644195   4576  55592       299  
3      GALAXY  0.932346   9149  58039       775  
4      GALAXY  0.116123   6121  56187       842  
...       ...       ...    ...    ...       ...  
99995  GALAXY  0.000000   9374  57749       438  
99996  GALAXY  0.404895   7626  56934       866  
99997  GALAXY  0.143366   2764  54535        74  
99998  GALAXY  0.455040   6751  56368       470  
99999  GALAXY  0.542944   7410  57104       851  

[100000 rows x 18 columns]

## Pre-processing

In [4]:
df.columns

Index(['obj_ID', 'alpha', 'delta', 'u', 'g', 'r', 'i', 'z', 'run_ID',
       'rerun_ID', 'cam_col', 'field_ID', 'spec_obj_ID', 'class', 'redshift',
       'plate', 'MJD', 'fiber_ID'],
      dtype='object')

In [5]:
df.describe()

obj_ID          alpha          delta              u  \
count  1.000000e+05  100000.000000  100000.000000  100000.000000   
mean   1.237665e+18     177.629117      24.135305      21.980468   
std    8.438560e+12      96.502241      19.644665      31.769291   
min    1.237646e+18       0.005528     -18.785328   -9999.000000   
25%    1.237659e+18     127.518222       5.146771      20.352353   
50%    1.237663e+18     180.900700      23.645922      22.179135   
75%    1.237668e+18     233.895005      39.901550      23.687440   
max    1.237681e+18     359.999810      83.000519      32.781390   

                   g              r              i              z  \
count  100000.000000  100000.000000  100000.000000  100000.000000   
mean       20.531387      19.645762      19.084854      18.668810   
std        31.750292       1.854760       1.757895      31.728152   
min     -9999.000000       9.822070       9.469903   -9999.000000   
25%        18.965230      18.135828      17.732285      17.460677   
50%        21.099835      20.125290      19.405145      19.004595   
75%        22.123767      21.044785      20.396495      19.921120   
max        31.602240      29.571860      32.141470      29.383740   

              run_ID  rerun_ID        cam_col       field_ID   spec_obj_ID  \
count  100000.000000  100000.0  100000.000000  100000.000000  1.000000e+05   
mean     4481.366060     301.0       3.511610     186.130520  5.783882e+18   
std      1964.764593       0.0       1.586912     149.011073  3.324016e+18   
min       109.000000     301.0       1.000000      11.000000  2.995191e+17   
25%      3187.000000     301.0       2.000000      82.000000  2.844138e+18   
50%      4188.000000     301.0       4.000000     146.000000  5.614883e+18   
75%      5326.000000     301.0       5.000000     241.000000  8.332144e+18   
max      8162.000000     301.0       6.000000     989.000000  1.412694e+19   

            redshift          plate            MJD       fiber_ID  
count  100000.000000  100000.000000  100000.000000  100000.000000  
mean        0.576661    5137.009660   55588.647500     449.312740  
std         0.730707    2952.303351    1808.484233     272.498404  
min        -0.009971     266.000000   51608.000000       1.000000  
25%         0.054517    2526.000000   54234.000000     221.000000  
50%         0.424173    4987.000000   55868.500000     433.000000  
75%         0.704154    7400.250000   56777.000000     645.000000  
max         7.011245   12547.000000   58932.000000    1000.000000

In [6]:
# Looking for data types and checking whether datas from columns is null or not
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   obj_ID       100000 non-null  float64
 1   alpha        100000 non-null  float64
 2   delta        100000 non-null  float64
 3   u            100000 non-null  float64
 4   g            100000 non-null  float64
 5   r            100000 non-null  float64
 6   i            100000 non-null  float64
 7   z            100000 non-null  float64
 8   run_ID       100000 non-null  int64  
 9   rerun_ID     100000 non-null  int64  
 10  cam_col      100000 non-null  int64  
 11  field_ID     100000 non-null  int64  
 12  spec_obj_ID  100000 non-null  float64
 13  class        100000 non-null  object 
 14  redshift     100000 non-null  float64
 15  plate        100000 non-null  int64  
 16  MJD          100000 non-null  int64  
 17  fiber_ID     100000 non-null  int64  
dtypes: float64(10), int64(7),

In [7]:
# data type conversion for consistency between data types
df['run_ID'] = df['run_ID'].astype(float)
df['rerun_ID'] = df['rerun_ID'].astype(float)
df['cam_col'] = df['cam_col'].astype(float)
df['field_ID'] = df['field_ID'].astype(float)
df['plate'] = df['plate'].astype(float)
df['MJD'] = df['MJD'].astype(float)
df['fiber_ID'] = df['fiber_ID'].astype(float)


In [8]:
#Looking for if columns attributes are unique or not
for column_name in df.columns:
    column_data = df[column_name]
    is_unique = column_data.nunique() == len(column_data)
    if is_unique:
        print('Column ' + column_name + ' contains unique values.')
    else:
        print('Column ' + column_name + ' does not contain unique values.')

Column obj_ID does not contain unique values.
Column alpha does not contain unique values.
Column delta does not contain unique values.
Column u does not contain unique values.
Column g does not contain unique values.
Column r does not contain unique values.
Column i does not contain unique values.
Column z does not contain unique values.
Column run_ID does not contain unique values.
Column rerun_ID does not contain unique values.
Column cam_col does not contain unique values.
Column field_ID does not contain unique values.
Column spec_obj_ID contains unique values.
Column class does not contain unique values.
Column redshift does not contain unique values.
Column plate does not contain unique values.
Column MJD does not contain unique values.
Column fiber_ID does not contain unique values.


In [9]:
# Deleting unique column from data set
df = df.drop("spec_obj_ID", axis=1)

In [10]:
df["class"].unique()

array(['GALAXY', 'QSO', 'STAR'], dtype=object)

In [11]:
df['class'].value_counts()

class
GALAXY    59445
STAR      21594
QSO       18961
Name: count, dtype: int64

In [12]:
df["class"] = df["class"].map({"GALAXY":0,"QSO":1, "STAR":2})

In [13]:
X = df.drop("class", axis=1)
y = df["class"]

## Split the dataset

In [14]:
# %80 percent Training %20 Testing
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

## kNN

In [15]:
# import necessary libary for kNN
from sklearn.neighbors import KNeighborsClassifier

In [16]:
knn = KNeighborsClassifier(n_neighbors=3)

In [17]:
knn = knn.fit(X_train, y_train)

In [18]:
knn_pred = knn.predict(X_test)

In [19]:
print(classification_report(y_test, knn_pred))

              precision    recall  f1-score   support

           0       0.63      0.87      0.73     11860
           1       0.29      0.15      0.20      3797
           2       0.45      0.16      0.24      4343

    accuracy                           0.58     20000
   macro avg       0.46      0.40      0.39     20000
weighted avg       0.53      0.58      0.52     20000



In [20]:
print(confusion_matrix(y_test, knn_pred))

[[10353   984   523]
 [ 2875   588   334]
 [ 3158   484   701]]


## Naive Bayes

In [21]:
# import necessary libary for Naive Bayes
from sklearn.naive_bayes import GaussianNB

In [22]:
nb = GaussianNB()

In [23]:
nb= nb.fit(X_train,y_train)

In [24]:
nb_pred = nb.predict(X_test)

In [25]:
print(classification_report(y_test,nb_pred))

              precision    recall  f1-score   support

           0       0.59      1.00      0.74     11860
           1       0.00      0.00      0.00      3797
           2       0.00      0.00      0.00      4343

    accuracy                           0.59     20000
   macro avg       0.20      0.33      0.25     20000
weighted avg       0.35      0.59      0.44     20000



/Users/oguzhantasci/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/oguzhantasci/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/oguzhantasci/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [26]:
print(confusion_matrix(y_test,nb_pred))

[[11860     0     0]
 [ 3797     0     0]
 [ 4343     0     0]]


## Random Forest

In [27]:
# import necessary libary for Random Forest
from sklearn.ensemble import RandomForestClassifier

In [28]:
rf= RandomForestClassifier(n_estimators=100,random_state=42)

In [29]:
rf = rf.fit(X_train, y_train)

In [30]:
rf_pred=rf.predict(X_test)

In [31]:
print(classification_report(y_test,rf_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98     11860
           1       0.97      0.93      0.95      3797
           2       0.99      1.00      1.00      4343

    accuracy                           0.98     20000
   macro avg       0.98      0.97      0.97     20000
weighted avg       0.98      0.98      0.98     20000



In [32]:
print(confusion_matrix(y_test,rf_pred))

[[11712   125    23]
 [  282  3514     1]
 [    2     0  4341]]


## SVM

In [33]:
from sklearn.svm import SVC

In [34]:
svm = SVC()

In [35]:
svm = svm.fit(X_train,y_train)

In [36]:
svm_pred = svm.predict(X_test)

In [37]:
print(classification_report(y_test,svm_pred))

              precision    recall  f1-score   support

           0       0.59      1.00      0.74     11860
           1       0.00      0.00      0.00      3797
           2       0.00      0.00      0.00      4343

    accuracy                           0.59     20000
   macro avg       0.20      0.33      0.25     20000
weighted avg       0.35      0.59      0.44     20000



/Users/oguzhantasci/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/oguzhantasci/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/oguzhantasci/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [38]:
print(confusion_matrix(y_test,svm_pred))

[[11860     0     0]
 [ 3797     0     0]
 [ 4343     0     0]]


## 5-fold cross validation

## kNN 

In [39]:
from sklearn.model_selection import cross_val_score, KFold

In [40]:
knn_5_fold = KNeighborsClassifier(n_neighbors=3)

In [41]:
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)

In [42]:
scores = cross_val_score(knn_5_fold, X_train, y_train, cv=kf)

In [43]:
print(f'Cross-validation scores: {scores}')
print(f'Average accuracy: {np.mean(scores):.2f}')

Cross-validation scores: [0.580125 0.565375 0.574875 0.583625 0.592625]
Average accuracy: 0.58


## Naive Bayes

In [44]:
nb_5_fold = GaussianNB()

In [45]:
scores = cross_val_score(nb_5_fold, X_train, y_train, cv=kf)

In [46]:
print(f'Cross-validation scores: {scores}')
print(f'Average accuracy: {np.mean(scores):.2f}')

Cross-validation scores: [0.5900625 0.5978125 0.5938125 0.594375  0.598    ]
Average accuracy: 0.59


## Random Forest

In [47]:
rf_5_fold = RandomForestClassifier(n_estimators=100,random_state=42)

In [48]:
scores = cross_val_score(rf_5_fold, X_train, y_train, cv=kf)

In [49]:
print(f'Cross-validation scores: {scores}')
print(f'Average accuracy: {np.mean(scores):.2f}')

Cross-validation scores: [0.9784375 0.9775625 0.9800625 0.9786875 0.978375 ]
Average accuracy: 0.98


## SVM

In [50]:
svm_5_fold = SVC()

In [ ]:
scores = cross_val_score(svm_5_fold, X_train, y_train, cv=kf)

In [ ]:
print(f'Cross-validation scores: {scores}')
print(f'Average accuracy: {np.mean(scores):.2f}')